# Generated by Django 3.2 on 2021-05-12 16:50

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blog_api.models.upload_to, verbose_name='Image'),
        ),
    ]
