# Generated by Django 3.2 on 2021-05-18 06:53

import api.cards_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='cards/default.jpg', upload_to=api.cards_api.models.upload_to, verbose_name='Pass Image')),
                ('descripion', models.TextField()),
                ('price_per_month', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Passes',
                'ordering': ('-price_per_month',),
            },
        ),
    ]
