# Generated by Django 3.2 on 2021-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pass',
            name='price_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
