# Generated by Django 3.2 on 2021-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_api', '0002_auto_20210526_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='with_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
