# Generated by Django 3.2 on 2021-05-27 09:37

import api.accounts_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='users/avatars/default.png', upload_to=api.accounts_api.models.upload_to, verbose_name='Avatar')),
            ],
        ),
    ]
