# Generated by Django 3.2 on 2021-05-29 10:48

import api.subscription_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards_api', '0002_auto_20210526_1944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=api.subscription_api.models.month_hence)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards_api.pass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
