# Generated by Django 3.2 on 2021-05-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ('-price_per_month',), 'verbose_name_plural': 'Passes'},
        ),
    ]
