# Generated by Django 3.2 on 2021-05-12 18:44

import cards_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_api', '0002_alter_pass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='image',
            field=models.ImageField(default='cards/default.jpg', upload_to=cards_api.models.upload_to, verbose_name='Image'),
        ),
    ]
